export const SET_CURRENT_USER = 'SET_CURRENT_USER';

export const SIGN_UP_FAILED = 'SIGN_UP_FAILED';

export const GET_NOT_RETURNED_BOOKS_COUNT = 'GET_NOT_RETURNED_BOOKS_COUNT';

export const CREATE_CATEGORY_SUCCESSFUL = 'CREATE_CATEGORY_SUCCESSFUL';

export const CREATE_CATEGORY_FAILED = 'CREATE_CATEGORY_FAILED';

export const GET_CATEGORY_COUNT = 'GET_CATEGORY_COUNT';

export const PUT_BOOKS = 'PUT_BOOKS';

// Done actions

export const GET_BOOKS_COUNT = 'GET_BOOKS_COUNT';

export const GET_RENTED_BOOKS_COUNT = 'GET_RENTED_BOOKS_COUNT';

export const COUNT_USERS = 'COUNT_USERS';

// Save image from cloudinary

export const SAVE_IMAGE_SUCCESSFUL = 'SAVE_IMAGE_SUCCESSFUL';

export const SAVE_IMAGE_FAILED = 'SAVE_IMAGE_FAILED';

export const SAVE_IMAGE_REQUEST = 'SAVE_IMAGE_REQUEST';

// Admin Add Books

export const CREATE_BOOKS_SUCCESSFUL = 'CREATE_BOOKS_SUCCESSFUL';

export const CREATE_BOOKS_FAILED = 'CREATE_BOOKS_FAILED';

export const CREATE_BOOKS_REQUEST = 'CREATE_BOOKS_REQUEST';

// Admin Delete Books

export const DELETE_BOOKS_SUCCESSFUL = 'DELETE_BOOKS_SUCCESSFUL';

export const DELETE_BOOKS_FAILED = 'DELETE_BOOKS_FAILED';

export const DELETE_BOOKS_REQUEST = 'DELETE_BOOKS_REQUEST';

// Admin Modify Books

export const MODIFY_BOOKS_SUCCESSFUL = 'MODIFY_BOOKS_SUCCESSFUL';

export const MODIFY_BOOKS_FAILED = 'MODIFY_BOOKS_FAILED';

export const MODIFY_BOOKS_REQUEST = 'MODIFY_BOOKS_REQUEST';

// User get all books

export const GET_BOOKS_SUCCESSFUL = 'GET_BOOKS_SUCCESSFUL';

export const GET_BOOKS_FAILED = 'GET_BOOKS_FAILED';

export const GET_BOOKS_REQUEST = 'GET_BOOKS_REQUEST';

// Admin get borrowed books

export const GET_BORROWED_BOOKS_SUCCESSFUL = 'GET_BORROWED_BOOKS_SUCCESSFUL';

export const GET_BORROWED_BOOKS_FAILED = 'GET_BORROWED_BOOKS_FAILED';

export const GET_BORROWED_BOOKS_REQUEST = 'GET_BORROWED_BOOKS_REQUEST';

// Admin get a book

export const GET_A_BOOK_SUCCESSFUL = 'GET_A_BOOK_SUCCESSFUL';

export const GET_A_BOOK_FAILED = 'GET_A_BOOK_FAILED';

export const GET_A_BOOK_REQUEST = 'GET_A_BOOK_REQUEST';

// Admin get book Id

export const EDIT_BOOK_ID = 'EDIT_BOOK_ID';

// Admin get category

export const GET_CATEGORY_SUCCESSFUL = 'GET_CATEGORY_SUCCESSFUL';

export const GET_CATEGORY_FAILED = 'GET_CATEGORY_FAILED';

export const GET_CATEGORY_REQUEST = 'GET_CATEGORY_REQUEST';

// Get user

export const GET_USER_SUCCESSFUL = 'GET_USER_SUCCESSFUL';

export const GET_USER_FAILED = 'GET_USER_FAILED';

export const GET_USER_REQUEST = 'GET_USER_REQUEST';

// Update Password

export const UPDATE_PASSWORD_SUCCESSFUL = 'UPDATE_PASSWORD_SUCCESSFUL';

export const UPDATE_PASSWORD_FAILED = 'UPDATE_PASSWORD_FAILED';

export const UPDATE_PASSWORD_REQUEST = 'UPDATE_PASSWORD_REQUEST';

// Update Password

export const BORROW_BOOKS_SUCCESSFUL = 'BORROW_BOOKS_SUCCESSFUL';

export const BORROW_BOOKS_FAILED = 'BORROW_BOOKS_FAILED';

export const BORROW_BOOKS_REQUEST = 'BORROW_BOOKS_REQUEST';

// List User Borrowed Books

export const GET_USER_BORROWED_SUCCESSFUL = 'GET_USER_BORROWED_SUCCESSFUL';

export const GET_USER_BORROWED_FAILED = 'GET_USER_BORROWED_FAILED';

export const GET_USER_BORROWED_REQUEST = 'GET_USER_BORROWED_REQUEST';

// List User Unreturned Books

export const YET_TO_RETURN_SUCCESSFUL = 'YET_TO_RETURN_SUCCESSFUL';

export const YET_TO_RETURN_FAILED = 'YET_TO_RETURN_FAILED';

export const YET_TO_RETURN_REQUEST = 'YET_TO_RETURN_REQUEST';

// List User Unreturned Books

export const RETURN_BOOK_SUCCESSFUL = 'RETURN_BOOK_SUCCESSFUL';

export const RETURN_BOOK_FAILED = 'RETURN_BOOK_FAILED';

export const RETURN_BOOK_REQUEST = 'RETURN_BOOK_REQUEST';
